site_name: Ramses Documentation
site_url: https://rainboxlab.org
repo_url: https://github.com/Rainbox-dev/Ramses/
edit_uri: edit/master/src-docs/docs/
site_description: The Ramses comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020 <a href="https://rainboxlagb.org">Rainbox Laboratory</a> and <a href="https://duduf.com">Nicolas Dufresne</a>'
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - Ramses: index.md
    - Components:
        - Ramses components: components/index.md
    - Installation:
        - Ramses Server: install/server.md
    - General help:
        - Ramses: help/index.md
        - Users: help/users.md
        - Projects: help/projects.md
        - Steps: help/steps.md
        - Asset Groups: help/assetgroups.md
        - Assets: help/assets.md
        - Sequences: help/sequences.md
        - Shots: help/shots.md
        - Status History: help/statushistory.md
        - Status: help/status.md
        - States: help/states.md
        - File Types: help/filetypes.md
        - Applications: help/applications.md
        - Pipeline: help/pipeline.md
    - Ramses Tree (File & Folders):
        - Naming scheme: files/naming.md
        - Folder structure: files/tree.md
    - Ramses Add-ons:
        - Add-ons in applications: addons/index.md
    - Development:
        - Introduction: dev/index.md
        - Files and Folders:
            - Naming: dev/files/naming.md
        - Scripting API (Add-ons):
            - Reference: dev/add-ons-reference/index.md
            - Ramses: dev/add-ons-reference/ramses.md
            - RamAsset: dev/add-ons-reference/ram_asset.md
            - RamDaemonInterface: dev/add-ons-reference/ram_daemon_interface.md
            - RamFileType: dev/add-ons-reference/ram_filetype.md
            - RamItem: dev/add-ons-reference/ram_item.md
            - RamObject: dev/add-ons-reference/ram_object.md
            - RamPipe: dev/add-ons-reference/ram_pipe.md
            - RamProject: dev/add-ons-reference/ram_project.md
            - RamSettings: dev/add-ons-reference/ram_settings.md
            - RamShot: dev/add-ons-reference/ram_shot.md
            - RamState: dev/add-ons-reference/ram_state.md
            - RamStatus: dev/add-ons-reference/ram_status.md
            - RamStep: dev/add-ons-reference/ram_step.md
            - RamUser: dev/add-ons-reference/ram_user.md
        - Daemon API:
            - Reference: dev/daemon-reference/index.md
            - Queries: dev/daemon-reference/queries.md
        - Server API:
            - Reference: dev/server-reference/index.md
            - General queries: dev/server-reference/general.md
            - User queries: dev/server-reference/users.md
            - Project queries: dev/server-reference/projects.md
            - Step queries: dev/server-reference/steps.md
            - Asset Group queries: dev/server-reference/assetgroups.md
            - Asset queries: dev/server-reference/assets.md
            - Sequence queries: dev/server-reference/sequences.md
            - Shot queries: dev/server-reference/shots.md
            - State queries: dev/server-reference/states.md
            - File type queries: dev/server-reference/filetypes.md
            - Application queries: dev/server-reference/applications.md
            - Pipe queries: dev/server-reference/pipes.md
    - Credits: credits.md
    - Changelog: changelog.md
    - License:
        - GNU GPLv3: licenses/gnu-gpl.md
        - Documentation license: licenses/gfdl.md
