site_name: Ramses
site_url: https://ramses.rxlab.guide
repo_url: https://github.com/Rainbox-dev/Ramses/
edit_uri: edit/master/src-docs/docs/
site_description: The Ramses comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright © 2020 <a href="https://rainboxlagb.org">Rainbox Laboratory</a> and <a href="https://duduf.com">Nicolas Dufresne</a>'
theme:
    name: null
    custom_dir: 'cinder'
    colorscheme: zenburn
extra:
    collapse_toc: true
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - fenced_code
    - toc
    - attr_list
extra_css:
    - style.css
    - video.css
extra_javascript:
    - video.js
    - meta.js
    - collapser.js
site_dir: ../docs/
dev_addr: '127.0.0.1:8001'
nav:
    - Ramses: index.md
    - Pipeline & Management:
        - Introduction: pipeline/index.md
        - Administration: pipeline/administration.md
        - User Management: pipeline/users.md
        - Pipeline: pipeline/pipeline.md
        - Production tracking: pipeline/production.md
        - Planning: pipeline/planning.md
    - Components:
        - Introduction: components/index.md
        - Ramses Server:
            - Introduction: components/server/index.md
            - A web server: components/server/web-server.md
            - Installation: components/server/install.md
            - Administration: components/server/admin.md
        - Ramses Application:
            - Installation and settings: .
            - Administration: .
            - Project settings: .
            - The pipeline: .
            - Assets and shots production management: .
            - Schedule and statistics: .
        - Ramses Add-ons:
            - General Information: addons/index.md
            - Autodesk Maya:
                - Ramses Add-on: addons/maya.md
                - Extensibility: addons/maya.md
                - Rubika Flavor: addons/maya.md
        - Ramses Tree:
            - Introduction: .
            - Naming scheme: files/naming.md
            - Folder structure: files/tree.md
    - Development:
        - Introduction: dev/index.md
        - Files and Folders:
            - Naming: dev/files/naming.md
        - Scripting API (Add-ons):
            - Reference: dev/add-ons-reference/index.md
            - Constants: dev/add-ons-reference/enum.md
            - Ramses: dev/add-ons-reference/ramses.md
            - RamAsset: dev/add-ons-reference/ram_asset.md
            - RamDaemonInterface: dev/add-ons-reference/ram_daemon_interface.md
            - RamFileManager: dev/add-ons-reference/ram_file_manager.md
            - RamFileType: dev/add-ons-reference/ram_filetype.md
            - RamItem: dev/add-ons-reference/ram_item.md
            - RamMetaDataManager: dev/add-ons-reference/ram_metadata_manager.md
            - RamObject: dev/add-ons-reference/ram_object.md
            - RamPipe: dev/add-ons-reference/ram_pipe.md
            - RamPipeFile: dev/add-ons-reference/ram_pipefile.md
            - RamProject: dev/add-ons-reference/ram_project.md
            - RamSettings: dev/add-ons-reference/ram_settings.md
            - RamShot: dev/add-ons-reference/ram_shot.md
            - RamState: dev/add-ons-reference/ram_state.md
            - RamStatus: dev/add-ons-reference/ram_status.md
            - RamStep: dev/add-ons-reference/ram_step.md
            - RamUser: dev/add-ons-reference/ram_user.md
            - Dev Notes: dev/add-ons-reference/implementation.md
        - Daemon API:
            - Reference: dev/daemon-reference/index.md
            - General queries: dev/daemon-reference/general_q.md
            - Asset queries: dev/daemon-reference/asset_q.md
            - Pipe queries: dev/daemon-reference/pipe_q.md
            - Project queries: dev/daemon-reference/project_q.md
            - Shot queries: dev/daemon-reference/shot_q.md
            - State and Status queries: dev/daemon-reference/state_q.md
            - Step queries: dev/daemon-reference/step_q.md
            - User queries: dev/daemon-reference/user_q.md
        - Server API:
            - Reference: dev/server-reference/index.md
            - Application queries: dev/server-reference/applications.md
            - Asset queries: dev/server-reference/assets.md
            - Asset Group queries: dev/server-reference/assetgroups.md
            - File type queries: dev/server-reference/filetypes.md
            - General queries: dev/server-reference/general.md
            - Pipe queries: dev/server-reference/pipes.md
            - PipeFiles queries: dev/server-reference/pipefiles.md
            - Project queries: dev/server-reference/projects.md
            - Sequence queries: dev/server-reference/sequences.md
            - Shot queries: dev/server-reference/shots.md
            - State queries: dev/server-reference/states.md
            - Status queries: dev/server-reference/status.md
            - Step queries: dev/server-reference/steps.md
            - User queries: dev/server-reference/users.md
    - ...:
        - Credits: credits.md
        - Changelog: changelog.md
        - Licenses:
            - GNU GPLv3: licenses/gnu-gpl.md
            - Documentation license: licenses/gfdl.md
